export default {
  defaults: {
    id: undefined,
    author: undefined,
    timeEntryBillable: undefined,
    name: undefined,
    duration: undefined,
    matter: undefined,
    timeEntryDate: undefined,
    created: undefined,
    details: undefined,
    activity: undefined,
    bill: undefined,
    approvedDuration: undefined,
    approvedDate: undefined,
    utbms: undefined,
    timeEntryStatus: undefined,
    rate: undefined,
    approveRate: undefined,
    deleted: undefined,
    sumRecord: undefined,
    approvedSumRecord: undefined,
    haveTime: undefined,
    timeEntryEndDate: undefined,
  },
  mapServerDataToIds: true,
}