import { RestifyForeignKey, RestifyForeignKeysArray } from 'redux-restify'
import { messages } from '$trood/mainConstants'
export default {
  defaults: {
    id: undefined,
    name: undefined,
    position: new RestifyForeignKey('employeePosition'),
    role: new RestifyForeignKey('employeeRole'),
    email: undefined,
    rate: undefined,
    account: undefined,
    active: undefined,
    created: undefined,
    avatar: undefined,
    phone: undefined,
    totalRating: undefined,
    clientSet: new RestifyForeignKeysArray('client', { allowNested: false }),
    candidateSet: new RestifyForeignKeysArray('candidate', { allowNested: false }),
    matterSet: new RestifyForeignKeysArray('matter', { allowNested: false }),
    matterInfoSet: new RestifyForeignKeysArray('matterInfo', { allowNested: false }),
    requestVacationSet: new RestifyForeignKeysArray('requestVacation', { allowNested: false }),
    vacancySet: new RestifyForeignKeysArray('vacancy', { allowNested: false }),
    vacancyCandidateSet: new RestifyForeignKeysArray('vacancyCandidate', { allowNested: false }),
    activitySet: new RestifyForeignKeysArray('activity', { allowNested: false }),
    billSet: new RestifyForeignKeysArray('bill', { allowNested: false }),
    invoiceSet: new RestifyForeignKeysArray('invoice', { allowNested: false }),
    paymentSet: new RestifyForeignKeysArray('payment', { allowNested: false }),
    timeEntrySet: new RestifyForeignKeysArray('timeEntry', { allowNested: false }),
    priceSet: new RestifyForeignKeysArray('price', { allowNested: false }),
    expenseSet: new RestifyForeignKeysArray('expense', { allowNested: false }),
    commentSet: new RestifyForeignKeysArray('comment', { allowNested: false }),
    matterEmployeeSet: new RestifyForeignKeysArray('matterEmployee', { allowNested: false }),
    billPriceListEmployeeSet: new RestifyForeignKeysArray('billPriceListEmployee', { allowNested: false }),
    invitationListEmployeeSet: new RestifyForeignKeysArray('invitationListEmployee', { allowNested: false }),
    contactSet: new RestifyForeignKeysArray('contact', { allowNested: false }),
    cvRecordSet: new RestifyForeignKeysArray('cvRecord', { allowNested: false }),
    documentSet: new RestifyForeignKeysArray('document', { allowNested: false }),
    approverSet: new RestifyForeignKeysArray('approver', { allowNested: false }),
    vacationPeriodSet: new RestifyForeignKeysArray('vacationPeriod', { allowNested: false }),
    timerSet: new RestifyForeignKeysArray('timer', { allowNested: false }),
    teamMemberSet: new RestifyForeignKeysArray('teamMember', { allowNested: false }),
  },
  name: 'employee',
  deletion: {
    confirm: true,
    message: messages.deletionQuestion,
  },
}