export default {
  defaults: {
    id: undefined,
    name: undefined,
    responsible: undefined,
    executor: undefined,
    activityStatus: undefined,
    matter: undefined,
    important: undefined,
    created: undefined,
    details: undefined,
    start: undefined,
    deadline: undefined,
    deleted: undefined,
    documentSet: [],
    commentSet: [],
    timeEntrySet: [],
    activityType: undefined,
    invitationList: undefined,
    timerSet: [],
    activityAccessStatus: undefined,
    haveTime: undefined,
  },
  mapServerDataToIds: true,
}