export default {
  defaults: {
    id: undefined,
    code: undefined,
    name: undefined,
    responsible: undefined,
    client: undefined,
    matterType: undefined,
    matterStatus: undefined,
    matterActiveStatus: undefined,
    budgetType: undefined,
    contactPersons: [],
    description: undefined,
    amount: undefined,
    created: undefined,
    totalBillAmount: undefined,
    startDate: undefined,
    endDate: undefined,
    activitySet: [],
    billSet: [],
    paymentSet: [],
    timeEntrySet: [],
    expenseSet: [],
    billPriceListSet: [],
    documentSet: [],
    matterContactPersonSet: [],
    commentSet: [],
    matterInfoSet: [],
    teamMemberSet: [],
  },
  mapServerDataToIds: true,
}